FROM node:alpine

EXPOSE 9102

ENV PRIVATE_KEY $PRIVATE_KEY
ENV SUBSTREAMS_API_TOKEN $SUBSTREAMS_API_TOKEN
ENV URL $URL
ENV CHAIN $CHAIN
ENV SPKG $SPKG
ENV MODULE_NAME $MODULE_NAME
ENV START_BLOCK $START_BLOCK
ENV PARAM $PARAM
ENV VERBOSE $VERBOSE

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

ENTRYPOINT ["node", "dist/bin/cli.js"]
